# Generated by Django 4.0.5 on 2022-06-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='date_added',
            field=models.DateField(auto_now_add=True, default='2006-10-25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industry',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='image',
            field=models.FileField(default=1, upload_to='industry/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industry',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='industry',
            name='name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
