# Generated by Django 4.0.5 on 2022-06-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_industry_date_added_industry_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name_plural': 'Industries'},
        ),
    ]
