# Generated by Django 4.0.5 on 2022-06-22 15:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productvariant_options_alter_product_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_resource',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='test_method',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
